# Generated by Django 3.2.20 on 2023-07-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
