# Generated by Django 3.2.20 on 2023-07-31 13:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
