# Generated by Django 3.2.20 on 2023-07-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0004_alter_post_body_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(max_length=255),
        ),
    ]
