# Generated by Django 3.2.20 on 2023-09-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0007_auto_20230807_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_first_name',
            field=models.CharField(default='John', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='author_last_name',
            field=models.CharField(default='Smith', max_length=30),
        ),
    ]
