# Generated by Django 3.2.20 on 2023-09-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelblog', '0009_auto_20230917_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
